name: analytics
description: A Flutter package which adds analytics support

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  mocktail: ^0.1.1
  test: ^1.21.5
  very_good_analysis: ^3.0.1
