version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/analytics"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/avatar_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/face_geometry"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/image_compositor"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/image_loader"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/js_interop_utils"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/photobooth_rive"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/holobooth_ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/photos_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/holobooth_ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/platform_helper"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/tensorflow_models/tensorflow_models"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/tensorflow_models/tensorflow_models_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/tensorflow_models/tensorflow_models_web"
    schedule:
      interval: "daily"
    directory: "/packages/gif_compositor/gif_compositor"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/gif_compositor/gif_compositor_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/gif_compositor/gif_compositor_web"
    schedule:
      interval: "daily"
