include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - lib/firebase_options_dev.dart
    - lib/firebase_options_prod.dart
    - lib/**/*.gen.dart
linter:
  rules:
    public_member_api_docs: false
