name: holobooth
description: Holobooth app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.6.0-0.1.pre

dependencies:
  analytics_repository:
    path: packages/analytics_repository
  audio_session: ^0.1.10
  authentication_repository:
    path: packages/authentication_repository
  avatar_detector_repository:
    path: packages/avatar_detector_repository
  bloc: ^8.1.0
  camera: ^0.10.0+3
  clock: ^1.1.1
  collection: ^1.16.0
  convert_repository:
    path: packages/convert_repository
  cross_file: ^0.3.3+2
  download_repository:
    path: packages/download_repository
  equatable: ^2.0.5
  face_geometry:
    path: packages/face_geometry
  firebase_analytics_client:
    path: packages/firebase_analytics_client
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flame: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  holobooth_ui:
    path: packages/holobooth_ui
  intl: ^0.17.0
  just_audio: ^0.9.30
  meta: ^1.8.0
  platform_helper:
    path: packages/platform_helper
  rive: ^0.10.1
  screen_recorder: 0.2.0
  tensorflow_models:
    path: packages/tensorflow_models/tensorflow_models
  uuid: ^3.0.6
  video_player: ^2.4.10

dependency_overrides:
  camera:
    git:
      url: https://github.com/VGVentures/plugins
      path: packages/camera/camera
      ref: da722ef898b1da47c339a17653067e070bb8e608
  camera_web:
    git:
      url: https://github.com/VGVentures/plugins
      path: packages/camera/camera_web
      ref: da722ef898b1da47c339a17653067e070bb8e608
  screen_recorder:
    git:
      url: https://github.com/ueman/screenrecorder
      ref: b5efd033df719e3d81473c55b8f1eeec7fd9badd

dev_dependencies:
  alchemist: ^0.6.0-dev.1
  bloc_test: ^9.1.0
  camera_platform_interface: ^2.2.0
  flame_test: ^1.9.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.3
  url_launcher_platform_interface: ^2.1.0
  very_good_analysis: ^3.1.0
  video_player_platform_interface: ^6.0.1

flutter_gen:
  output: lib/assets/
  integrations:
    rive: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/audio/
    - assets/backgrounds/
    - assets/characters/
    - assets/icons/
    - assets/images/
    - assets/props/
