name: io_photobooth
description: I/O Photo Booth app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  alchemist: ^0.5.1
  analytics:
    path: packages/analytics
  audio_session: ^0.1.10
  authentication_repository:
    path: packages/authentication_repository
  avatar_detector_repository:
    path: packages/avatar_detector_repository
  bloc: ^8.1.0
  camera: ^0.10.0+3
  collection: ^1.16.0
  cross_file: ^0.3.3+2
  equatable: ^2.0.5
  face_geometry:
    path: packages/face_geometry
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_storage: ^10.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  image_compositor:
    path: packages/image_compositor
  intl: ^0.17.0
  js_interop_utils:
    path: packages/js_interop_utils
  just_audio: ^0.9.30
  meta: ^1.8.0
  photobooth_ui:
    path: packages/photobooth_ui
  photos_repository:
    path: packages/photos_repository
  platform_helper:
    path: packages/platform_helper
  rive: ^0.9.1
  rxdart: ^0.26.0
  tensorflow_models:
    path: packages/tensorflow_models/tensorflow_models
  uuid: ^3.0.6

dependency_overrides:
  camera:
    git:
      url: https://github.com/VGVentures/plugins
      path: packages/camera/camera
      ref: 795029b21f6c5ca9df2a0eb3ff1d5f288757141c
  camera_web:
    git:
      url: https://github.com/VGVentures/plugins
      path: packages/camera/camera_web
      ref: 795029b21f6c5ca9df2a0eb3ff1d5f288757141c

dev_dependencies:
  bloc_test: ^9.1.0
  camera_platform_interface: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.3
  url_launcher_platform_interface: ^2.1.0
  very_good_analysis: ^3.1.0

flutter_gen:
  output: lib/assets/
  integrations:
    rive: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/audio/
    - assets/backgrounds/
    - assets/characters/
    - assets/icons/
    - assets/images/
