name: io_photobooth
description: I/O Photo Booth app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  analytics:
    path: packages/analytics
  audio_session: ^0.1.10
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  camera: ^0.10.0+1
  cross_file: ^0.3.3+1
  equatable: ^2.0.5
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  image_compositor:
    path: packages/image_compositor
  intl: ^0.17.0
  js_interop_utils:
    path: packages/js_interop_utils
  just_audio: ^0.9.29
  photobooth_ui:
    path: packages/photobooth_ui
  photos_repository:
    path: packages/photos_repository
  platform_helper:
    path: packages/platform_helper
  rxdart: ^0.26.0
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  camera_platform_interface: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.3
  url_launcher_platform_interface: ^2.1.0
  very_good_analysis: ^3.1.0

flutter_gen:
  output: lib/assets/

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
    - assets/backgrounds/
    - assets/images/
    - assets/icons/
    - assets/props/google/
    - assets/props/hats/
    - assets/props/eyewear/
    - assets/props/food/
    - assets/props/shapes/
