name: gif_compositor_web
description: Web implementation of the gif_compositor plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.1"

flutter:
  plugin:
    implements: gif_compositor
    platforms:
      web:
        pluginClass: GifCompositorWeb
        fileName: gif_compositor_web.dart

dependencies:
  cross_file: ^0.3.3+2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  gif_compositor_platform_interface:
    path: ../gif_compositor_platform_interface
  image: ^3.2.0
  isolated_worker: ^0.1.1
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
