name: js_interop_utils
description: Package with Javascript functions needed for interop operations.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  js: ^0.6.4
