name: gif_compositor_platform_interface
description: A common platform interface for the gif_compositor plugin.
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cross_file: ^0.3.3+2
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  test: ^1.21.6
  very_good_analysis: ^3.1.0
