name: authentication_repository
description: Repository which manages user authentication using Firebase Authentication.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.4.0
