/// File partially autogenerated
/// Check readme on how to regenerate the file
/// https://github.com/VGVentures/Photo-Booth-V2/tree/main/packages/tensorflow_models/tensorflow_models_web#autogeneration-of-interop

import "package:js/js.dart";

@JS()
abstract class Promise<T> {
  external factory Promise(
      void executor(void resolve(T result), Function reject));
  external Promise then(void onFulfilled(T result), [Function onRejected]);
}
