name: tensorflow_models_platform_interface
description: A common platform interface for the tensorflow_models plugin.
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.5
  very_good_analysis: ^3.1.0
