name: photos_repository
description: repository that manages the photo domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  firebase_core: 1.0.4
  firebase_storage: 8.0.4
  flutter:
    sdk: flutter
  image_compositor:
    path: ../image_compositor

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.4.0
