name: firebase_analytics_client
description: A Flutter package which adds analytics support

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  mocktail: ^0.1.1
  test: ^1.21.5
  very_good_analysis: ^3.1.0
