name: avatar_detector_repository
description: Repository to give avatar information based on tensorflow implementation.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  tensorflow_models:
    path: ../tensorflow_models/tensorflow_models

dev_dependencies:
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  test: ^1.19.2
  very_good_analysis: ^3.1.0
