name: image_compositor
description: A Flutter package which adds image compositing support via web workers

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  image_loader:
    path: ../image_loader

dev_dependencies:
  mocktail: ^0.1.1
  test: ^1.21.5
  very_good_analysis: ^3.1.0
