name: tensorflow_models
description: A Flutter plugin for integrating pre-built tensorflow models.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

flutter:
  plugin:
    platforms:
      web:
        default_package: tensorflow_models_web

dependencies:
  face_geometry:
    path: ../../face_geometry
  flutter:
    sdk: flutter
  tensorflow_models_platform_interface:
    path: ../tensorflow_models_platform_interface
  tensorflow_models_web:
    path: ../tensorflow_models_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  plugin_platform_interface: ^2.1.2
  very_good_analysis: ^3.1.0
