name: photobooth_ui
description: UI Toolkit for the Photobooth Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.3.0
  flutter:
    sdk: flutter
  platform_helper:
    path: ../platform_helper
  url_launcher: ^6.1.5

dev_dependencies:
  alchemist: ^0.6.0-dev.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  plugin_platform_interface: ^2.1.3
  url_launcher_platform_interface: ^2.1.0
  very_good_analysis: ^3.1.0

flutter:
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
