name: screen_recorder
description: Package to create recordings of Flutter widgets.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  cross_file: ^0.3.3+2
  flutter:
    sdk: flutter
  gif_compositor:
    path: ../gif_compositor/gif_compositor
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
