name: example
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  camera:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
