name: analytics

on:
  pull_request:
    paths:
      - "packages/analytics/**"
      - ".github/workflows/analytics.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@72a170b9eeb872d03d8d7de1d99876c304371fbc
    with:
      platform: "chrome,vm"
      working_directory: packages/analytics