name: camera

on:
  pull_request:
    paths:
      - "packages/camera/camera/**"
      - ".github/workflows/camera.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.3.1
      working_directory: packages/camera/camera
