name: deploy_app_staging

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App Staging
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.4.0-34.1.pre"
          channel: "beta"
      - run: flutter packages get
      - run: flutter build web --web-renderer canvaskit
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PHOTOBOOTH_DEV }}"
          projectId: io-photobooth-dev
          target: app_staging
          expires: 30d
          channelId: live
