name: deploy_example_dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tensorflow_models/tensorflow_models/example

    name: Deploy Example Development
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter packages get
      - run: flutter build web --web-renderer canvaskit
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PHOTOBOOTH_DEV }}"
          projectId: io-photobooth-dev
          target: example_dev
          expires: 30d
          channelId: live
          entryPoint: packages/tensorflow_models/tensorflow_models/example
