name: photobooth_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/photobooth_ui/**"
      - ".github/workflows/photobooth_ui.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 2.4.0-4.2.pre
      coverage_excludes: "**/*.gen.dart"
      working_directory: packages/photobooth_ui
