name: holobooth_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/holobooth_ui/**"
      - ".github/workflows/holobooth_ui.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: "beta"
      flutter_version: 3.6.0-0.1.pre
      working_directory: packages/holobooth_ui
