name: platform_helper

on:
  pull_request:
    paths:
      - "packages/platform_helper/**"
      - ".github/workflows/platform_helper.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/platform_helper
