name: tensorflow_models

on:
  pull_request:
    paths:
      - "package/tensorflow_models/tensorflow_models/**"
      - ".github/workflows/tensorflow_models.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: "beta"
      flutter_version: 3.6.0-0.1.pre
      working_directory: packages/tensorflow_models/tensorflow_models
